name 'aws_gaming'
maintainer 'Tyler Ball'
maintainer_email 'tyleraball@gmail.com'
license 'all_rights'
description 'Installs/Configures aws_gaming'
long_description 'Installs/Configures aws_gaming'
version '0.1.0'
