name 'aws_gaming'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures aws_gaming'
long_description 'Installs/Configures aws_gaming'
version '0.1.0'
